module: Advance
author: Tim Donnelly
github_url: https://github.com/timdonnelly/Advance
github_file_prefix: https://github.com/timdonnelly/Advance/tree/master
root_url: https://timdonnelly.github.io/Advance
xcodebuild_arguments: [-scheme,Advance-iOS]
module_version: master
exclude: []

copyright: '© 2018 Tim Donnelly'


custom_categories:

  - name: Animation
    children:
    - PropertyAnimator
    - Animation
    - BasicAnimation
    - AnyAnimation
    - AnimationRunner

  - name: Simulation
    children:
    - Simulator
    - Spring
    - Simulation
    - SimulationFunction
    - SimulationState
    - Convergence
    - SpringFunction
    - DecayFunction
    - GravityFunction
    - SimulatedAnimation

  - name: Timing Functions
    children:
    - TimingFunction
    - LinearTimingFunction
    - ReversedTimingFunction
    - UnitBezier

  - name: Loop
    children:
    - Loop

  - name: Events
    children:
    - Observable
    - Subscription

  - name: Vectors
    children:
    - Vector
    - VectorConvertible
    - Interpolatable
    - Scalar
    - Vector1
    - Vector2
    - Vector3
    - Vector4

  - name: Extensions
    children:
    - Double
    - CAMediaTimingFunction
    - CGFloat
    - CGPoint
    - CGRect
    - CGSize
    - CGVector
    - Bool
    - Int
    - UIEdgeInsets
    - UIOffset

  - name: Advanceable
    children:
    - Advanceable