module: Advance
author: Tim Donnelly
github_url: https://github.com/timdonnelly/Advance
github_file_prefix: https://github.com/timdonnelly/Advance/tree/master
root_url: https://timdonnelly.github.io/Advance
xcodebuild_arguments: [-scheme,Advance-iOS]
module_version: master
exclude: []

copyright: '© 2018 Tim Donnelly'


custom_categories:

  - name: Animator
    children:
    - Animator

  - name: Simulator
    children:
    - Simulator
    - Spring 
  
  - name: Simulation
    children:
    - Simulation
    - SimulationState
    - SimulationFunction
    - Convergence
    - SpringFunction
    - DecayFunction
    - GravityFunction

  - name: Animations
    children:
    - Animator
    - Animation

  - name: Basic Animations
    children:
    - BasicAnimation
    - TimingFunction
    - LinearTimingFunction
    - ReversedTimingFunction
    - UnitBezier

  - name: Simulated Animations
    children:
    - SimulatedAnimation

  - name: Loop
    children:
    - Loop

  - name: Events
    children:
      - Observable

  - name: Vectors
    children:
    - Vector
    - VectorConvertible
    - Interpolatable
    - Scalar
    - Vector1
    - Vector2
    - Vector3
    - Vector4

  - name: Extensions
    children:
    - Double
    - CAMediaTimingFunction
    - CGFloat
    - CGPoint
    - CGRect
    - CGSize
    - CGVector

  - name: Advanceable
    children:
    - Advanceable