module: Advance
module_name: Advance
author: Storehouse
author_url: https://www.storehouse.co
github_url: https://github.com/storehouse/Advance
github-file-prefix: https://github.com/storehouse/Advance/tree/master
root-url: https://storehouse.github.io/Advance/docs
xcodebuild-arguments: -scheme,Advance
module-version: master
exclude: []

copyright: '© 2016 [Storehouse Media Inc](http://www.storehouse.co).'

swift_version: 2.2

custom_categories:
  - name: Animations
    children:
    - Advanceable
    - AnimationType
    - AnyValueAnimation
    - BasicAnimation
    - DecayAnimation
    - SpringAnimation
    - ValueAnimationType
  - name: Timing Functions
    children:
    - TimingFunctionType
    - LinearTimingFunction
    - ReversedTimingFunction
    - UnitBezier

  - name: Animation Helpers
    children:
    - Animatable
    - Animator
    - AnimatorContext
    - AnimatorResult
    - AnimatorState

  - name: Loop
    children:
    - Loop
    - LoopSubscription

  - name: Dynamics
    children:
    - DecayFunction
    - DynamicSolver
    - DynamicFunctionType
    - Spring
    - SpringFunction
    - SpringConfiguration

  - name: Events
    children:
      - Event
      - EventState

  - name: Vectors
    children:
    - Interpolatable
    - Scalar
    - VectorConvertible
    - VectorMathCapable
    - VectorType
    - Vector1
    - Vector2
    - Vector3
    - Vector4

  - name: Extensions
    children:
    - Double
    - CAMediaTimingFunction
    - CGFloat
    - CGPoint
    - CGRect
    - CGSize
    - CGVector
