osx_image: xcode11.2

jobs:
  include:
    - name: "iOS (SPM)"
      language: swift
      os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild -scheme "Advance" test -destination "name=iPhone 11"

    - name: "macOS (SPM)"
      language: swift
      os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild -scheme "Advance" test

    - name: "tvOS (SPM)"
      language: swift
      os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild -scheme "Advance" test -destination "name=Apple TV 4K"

    - name: "Linux (SPM)"
      sudo: required
      dist: trusty
      os: linux
      language: generic
      env:
        - SWIFT_VERSION=5.1
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift --version
        - swift build
        - swift test

      
