language: objective-c
osx_image: xcode9.2
script:
  - xcodebuild -project Advance.xcodeproj -scheme 'Advance-iOS' -configuration Debug -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2'
  - xcodebuild -project Advance.xcodeproj -scheme 'Advance-OSX' -configuration Debug test
